<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Daraban.Modules.Assets.Data\Daraban.Modules.Assets.Data.csproj" />
    <ProjectReference Include="..\..\..\Shared\Daraban.Platform.Common\Daraban.Platform.Common.csproj" />
    <ProjectReference Include="..\..\..\Shared\Daraban.Platform.Abstractions\Daraban.Platform.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Shared\Daraban.Platform.Contracts\Daraban.Platform.Contracts.csproj" />
  </ItemGroup>
</Project>
