<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>

  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Daraban.Modules.Financial.Services\Daraban.Modules.Financial.Services.csproj" />
  </ItemGroup>
</Project>
