<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <RootNamespace Condition="'$(RootNamespace)' == ''">$(MSBuildProjectName)</RootNamespace>
  </PropertyGroup>
</Project>
