<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Moq" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Modules\Software\Daraban.Modules.Software.Services\Daraban.Modules.Software.Services.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Software\Daraban.Modules.Software.Data\Daraban.Modules.Software.Data.csproj" />
  </ItemGroup>
</Project>
