<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>

  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Daraban.Modules.Notifications.Services\Daraban.Modules.Notifications.Services.csproj" />
    <ProjectReference Include="..\..\..\Shared\Daraban.Platform.Hosting\Daraban.Platform.Hosting.csproj" />
  </ItemGroup>
</Project>
