<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Daraban.Platform.Messaging\Daraban.Platform.Messaging.csproj" />
    <ProjectReference Include="..\..\Modules\Notifications\Daraban.Modules.Notifications.Services\Daraban.Modules.Notifications.Services.csproj" />
  </ItemGroup>
</Project>
