"""Write community labels JSON for graphify Step 5 relabeling."""
import json
from pathlib import Path

labels = {
    '0': 'Knowledge Base API', '1': 'Location Management API', '2': 'JWT Auth Infrastructure',
    '3': 'KB Ticket Solutions API', '4': 'Refresh Token Auth', '5': 'Ticket Templates',
    '6': 'Ticket Tasks', '7': 'Discovery DTOs', '8': 'Asset Categories',
    '9': 'Identity & Inventory Domains', '10': 'Ticket Frontend Models',
    '11': 'Agent UI Components', '12': 'Asset Assignments', '13': 'Ticket Entity',
    '14': 'IP Scanner Engine', '15': 'KB Articles', '16': 'Discovery Repositories',
    '17': 'SNMP Credentials API', '18': 'Asset Frontend Services', '19': 'KB Article Config',
    '20': 'Assets API', '21': 'Ticket Repository', '22': 'Asset Type Repository',
    '23': 'Discovery Repository Interface', '24': 'Assets Module', '25': 'Import Rules Service',
    '26': 'Ticket Enums', '27': 'Asset CSV Export', '28': 'Manufacturer Repository',
    '29': 'Financial Module', '30': 'Purchase Repository', '31': 'KB Events & Tests',
    '32': 'Asset Import Export Tests', '33': 'Auth Validation', '34': 'KB Feedback',
    '35': 'User Repository & Service', '36': 'Discovery Service', '37': 'Contracts',
    '38': 'Import Rule Tests', '39': 'Platform Hosting & Controllers', '40': 'KB Validators',
    '41': 'Discovery Module', '42': 'ServiceDesk Module', '43': 'Frontend Auth Store',
    '44': 'Infocom Config', '45': 'Asset Lifecycle', '46': 'Identity Auth Service',
    '47': 'Inventory Events', '48': 'KB Article Repository', '49': 'Agent Command Tests',
    '50': 'Knowledge Module', '51': 'Agent Command Service', '52': 'Raw Inventory Submissions',
    '53': 'User Service Tests', '54': 'Discovery Frontend', '55': 'Discovery Scans',
    '56': 'Purchase Config', '57': 'User Entity', '58': 'Validators Cross-Module',
    '59': 'SignalR Hubs', '60': 'Discovery Rule Config', '61': 'Platform Hosting Packages',
    '62': 'Asset Lifecycle API', '63': 'Discovered Devices', '64': 'Software Installations',
    '65': 'Purchase Service Tests', '66': 'Assets DbContext', '67': 'Discovery Frontend Service',
    '68': 'Asset Repository', '69': 'Software License Tests', '70': 'Credential Encryption',
    '71': 'Software License Config', '72': 'Import Rules', '73': 'Agent Entity',
    '74': 'Agent Service', '75': 'Software Installation Repo', '76': 'Budget Service Tests',
    '77': 'Ticket Workflow Tests', '78': 'Software Installation Tests', '79': 'Asset Fields',
    '80': 'Asset Status History', '81': 'Discovery Ranges', '82': 'Infocom Repository',
    '83': 'Agent Audit Logs', '84': 'Software License Repository', '85': 'Agent Inventory API',
    '86': 'Software Module', '87': 'RabbitMQ Messaging', '88': 'SNMP Discovery Engine',
    '89': 'Identity Packages', '90': 'Contract Repository', '91': 'Asset Assignment Tests',
    '92': 'Asset Assignments API', '93': 'KB Frontend', '94': 'TypeScript Config',
    '95': 'Discovery Scheduler', '96': 'Suppliers', '97': 'Software Repository',
    '98': 'Agent Command Contracts', '99': 'Asset Service Tests', '100': 'Depreciation Tests',
    '101': 'SNMP Discovery Results', '102': 'Tickets API', '103': 'Contract Tests',
    '104': 'Permission Resolver Tests', '105': 'Budgets API', '106': 'Budget Config',
    '107': 'Contract DTOs', '108': 'Budget Service', '109': 'Inventory Service',
    '110': 'Ticket Templates API', '111': 'Ticket Status Tests', '112': 'Knowledge Migrations',
    '113': 'Asset Import Service', '114': 'Infocom Service', '115': 'Supplier Service',
    '116': 'Agent Commands', '117': 'Inventory Repository', '118': 'Ticket Create Tests',
    '119': 'Angular Dev Dependencies', '120': 'Financial Config',
    '121': 'Discovery Result Processing', '122': 'App Bootstrap',
    '123': 'Host & Inventory Packages', '124': 'Contract Types',
    '125': 'Agent Service Interface', '126': 'Ticket History', '127': 'Ticket Validation',
    '128': 'Ticket Service', '129': 'Software License DTOs',
    '130': 'Agent Scope Authorization', '131': 'KB Category Config',
    '132': 'Asset Relationships', '133': 'Ticket Query Tests',
    '134': 'Software Installation DTOs', '135': 'Identity Config',
    '136': 'Agent Management API', '137': 'Assets Packages', '138': 'Agent Credentials',
    '139': 'KB Articles API', '140': 'Ticket Costs', '141': 'Supplier Service Tests',
    '142': 'Software Service Tests', '143': 'Assets Import API', '144': 'Asset Models',
    '145': 'Automation Packages', '146': 'Import Rule API', '147': 'Printer MIB Data',
    '148': 'Contract Config', '149': 'Purchase Items', '150': 'Supplier Config',
    '151': 'Agent Config', '152': 'Agent Command Repository', '153': 'Reporting Packages',
    '154': 'Ticket Task Service', '155': 'Software Config', '156': 'Angular Dependencies',
    '157': 'Solution Structure', '158': 'Discovery Packages', '159': 'Locations',
    '160': 'Financial Packages', '161': 'Budget Repository', '162': 'Paged List Utils',
    '163': 'Knowledge Packages', '164': 'Notifications Packages',
    '165': 'ServiceDesk Packages', '166': 'Software Products',
    '167': 'Network Map Component', '168': 'Agent Repository', '169': 'Discovery Result Processor',
    '170': 'Agent Auth Service', '171': 'Computers', '172': 'Software Installation Repo',
    '173': 'Discovery DbContext', '174': 'Discovery Range API', '175': 'Ticket Detail UI',
    '176': 'Asset Export API', '177': 'Asset Documents', '178': 'Asset Models',
    '179': 'Asset Types', '180': 'Port Mapping', '181': 'Purchases API', '182': 'Users API',
    '183': 'Agent Command Repository Iface', '184': 'Software Licenses API',
    '185': 'Software & Common Packages', '186': 'Asset Types API', '187': 'Docs Package',
    '188': 'Discovery Range UI', '189': 'Asset Field Values', '190': 'SNMP Engine Interface',
    '191': 'Infocoms API', '192': 'Contract Costs', '193': 'Depreciation', '194': 'Purchases',
    '195': 'Purchase Repository', '196': 'Inventory Repository',
    '197': 'Software License Repository', '198': 'Software Repository',
    '199': 'RabbitMQ Consumers', '200': 'Asset List UI', '201': 'Asset Categories API',
    '202': 'Manufacturers API', '203': 'Discovery Rule API', '204': 'Contracts API',
    '205': 'Budget Repository', '206': 'Supplier Repository', '207': 'Entity Nodes',
    '208': 'Identity DbContext', '209': 'Entity Scope Access',
    '210': 'Software Installations API', '211': 'Software API',
    '212': 'Permission Authorization', '213': 'Asset Detail UI',
    '214': 'Import Rule Editor UI', '215': 'Scan Results UI',
    '216': 'Global Exception Handler', '217': 'Assets DbContext Sets', '218': 'Suppliers API',
    '219': 'Entity Scope Tests', '220': 'Architecture Documentation',
    '221': 'Angular Build Config', '222': 'Followup UI', '223': 'Ticket List UI',
    '224': 'Knowledge DbContext', '225': 'Agent Events & Consumers',
    '226': 'Host API Packages', '227': 'Agent Repository Iface',
    '228': 'Notifications Module', '229': 'SLA Timer UI', '230': 'Agent Command API',
    '231': 'Admin Agent API', '232': 'Suppliers', '233': 'Purchase DTOs',
    '234': 'Profile Rights', '235': 'User Profile Entities', '236': 'Permission Resolver',
    '237': 'Agent Control Hub', '238': 'Ticket Tasks API', '239': 'Reporting Module',
    '240': 'Automation Module', '241': 'Docs Build Script', '242': 'Frontend Package',
    '243': 'Auth API', '244': 'JWT Token Service', '245': 'License Types',
    '246': 'Software DbContext', '247': 'Software Service', '248': 'Ticket Create UI',
    '249': 'App TS Config', '250': 'Spec TS Config', '251': 'CSV Converters',
    '252': 'Discovery Scan API', '253': 'Profiles', '254': 'ServiceDesk DbContext',
    '255': 'Persian Docs Community', '256': 'Angular Prod Config', '257': 'Serilog Config',
    '258': 'Dynamic Permission Policy', '259': 'Import Rule Config',
    '260': 'Agent Commands API', '261': 'Assignment Lookup API',
    '262': 'Discovery Dashboard API', '263': 'SNMP Interfaces',
    '264': 'Knowledge Query Tests', '265': 'Architecture Tests',
    '266': 'Angular Test Config', '267': 'Asset Import UI', '268': 'Scan Types',
    '269': 'Health Checks', '270': 'Agent Auth API', '271': 'Inventory DbContext',
    '272': 'Angular Workspace Config', '273': 'Device Detail UI', '274': 'Ticket Sources',
    '275': 'Ticket Hub Client', '276': 'Result Type', '277': 'Inventory Consumer',
    '278': 'Notification Consumer', '279': 'Command Timeout Service',
    '280': 'Angular Serve Config', '281': 'Scan Progress UI', '282': 'KB Article UI',
    '283': 'Architecture Test Packages', '284': 'SNMP Probe Results',
    '285': 'Angular Dev Config', '286': 'Angular Schematics', '287': 'Asset Form UI',
    '288': 'Match Actions', '289': 'Ticket Validation Status',
    '290': 'Problem Details Extensions', '291': 'Docker Stack', '292': 'SNMP Versions',
    '293': 'Ticket Impact', '294': 'Ticket Urgency', '295': 'SysDescr Parsing',
    '296': 'Guard Utilities', '297': 'Ticket Events', '298': 'Agent Knowledge',
    '299': 'Financial Assembly', '300': 'Identity Assembly', '301': 'Knowledge Assembly',
    '302': 'Software Assembly', '303': 'Automation Assembly', '304': 'Inventory Assembly',
    '305': 'Reporting Assembly', '306': 'Discovery Assembly', '307': 'ServiceDesk Assembly',
    '308': 'Assets Assembly', '309': 'Notifications Assembly', '310': 'Auth UI Pages',
    '315': 'PDF Build Artifacts', '316': 'Agent UI Pages', '320': 'Platform README',
}

out = {str(k): v for k, v in labels.items()}
Path('graphify-out/.graphify_labels_input.json').write_text(
    json.dumps(out, ensure_ascii=False), encoding='utf-8')
print('Labels written:', len(out))
