<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Daraban.Modules.Software.Services\Daraban.Modules.Software.Services.csproj" />
    <ProjectReference Include="..\..\Shared\Daraban.Platform.Abstractions\Daraban.Platform.Abstractions.csproj" />
  </ItemGroup>
</Project>
