using Daraban.Modules.Financial.Data.Entities;

namespace Daraban.Modules.Financial.Services.Dtos;

public record InfocomDto(
    Guid Id,
    Guid EntityId,
    Guid AssetId,
    string? PurchaseOrderNumber,
    string? InvoiceNumber,
    DateTimeOffset? PurchaseDate,
    DateTimeOffset? DeliveryDate,
    DateTimeOffset? UseDate,
    decimal PurchaseCost,
    decimal AdditionalCost,
    decimal TotalCost,
    string Currency,
    Guid? SupplierId,
    string? SupplierName,
    Guid? BudgetId,
    string? BudgetName,
    DepreciationMethod DepreciationMethod,
    int DepreciationDurationMonths,
    decimal? DepreciationCoefficient,
    bool DepreciationOnUseDate,
    decimal CurrentValue,
    decimal ResidualValue,
    DateTimeOffset? WarrantyStartDate,
    DateTimeOffset? WarrantyEndDate,
    string? WarrantyDetails,
    DateTimeOffset? InsuranceStartDate,
    DateTimeOffset? InsuranceEndDate,
    decimal? InsuranceValue,
    string? Comment,
    DateTimeOffset? DecommissionDate,
    decimal? SalePrice,
    bool IsActive,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public record InfocomListDto(
    Guid Id,
    Guid AssetId,
    string? PurchaseOrderNumber,
    string? InvoiceNumber,
    DateTimeOffset? PurchaseDate,
    decimal PurchaseCost,
    decimal CurrentValue,
    string? SupplierName,
    string? BudgetName);

public record InfocomPagedResult(
    IReadOnlyList<InfocomListDto> Items,
    int TotalCount,
    int Page,
    int PageSize);

public record CreateInfocomRequest(
    Guid EntityNodeId,
    Guid AssetId,
    string? PurchaseOrderNumber,
    string? InvoiceNumber,
    DateTimeOffset? PurchaseDate,
    DateTimeOffset? DeliveryDate,
    DateTimeOffset? UseDate,
    decimal PurchaseCost,
    decimal AdditionalCost,
    string Currency,
    Guid? SupplierId,
    Guid? BudgetId,
    DepreciationMethod DepreciationMethod,
    int DepreciationDurationMonths,
    decimal? DepreciationCoefficient,
    bool DepreciationOnUseDate,
    decimal ResidualValue,
    DateTimeOffset? WarrantyStartDate,
    DateTimeOffset? WarrantyEndDate,
    string? WarrantyDetails,
    DateTimeOffset? InsuranceStartDate,
    DateTimeOffset? InsuranceEndDate,
    decimal? InsuranceValue,
    string? Comment);

public record UpdateInfocomRequest(
    string? PurchaseOrderNumber,
    string? InvoiceNumber,
    DateTimeOffset? PurchaseDate,
    DateTimeOffset? DeliveryDate,
    DateTimeOffset? UseDate,
    decimal PurchaseCost,
    decimal AdditionalCost,
    string Currency,
    Guid? SupplierId,
    Guid? BudgetId,
    DepreciationMethod DepreciationMethod,
    int DepreciationDurationMonths,
    decimal? DepreciationCoefficient,
    bool DepreciationOnUseDate,
    decimal ResidualValue,
    DateTimeOffset? WarrantyStartDate,
    DateTimeOffset? WarrantyEndDate,
    string? WarrantyDetails,
    DateTimeOffset? InsuranceStartDate,
    DateTimeOffset? InsuranceEndDate,
    decimal? InsuranceValue,
    string? Comment);

public record DepreciationCalculationResult(
    Guid InfocomId,
    Guid AssetId,
    decimal TotalCost,
    decimal DepreciationAmount,
    decimal CurrentValue,
    decimal ResidualValue,
    int RemainingMonths,
    bool FullyDepreciated,
    DateTimeOffset DepreciationStartDate,
    DepreciationMethod Method);
